# US Census Demographic Analysis - Exploring tidyverse, readr, and ggplot2.

For the first project of the course, we were tasked with processing and manipulating US Census Bureau's data from 2010. The database for USA Counties features over 6,000 items. Files include data published for population estimates and many items from the 2000 and 2010 Census of Population and Housing, the American Community Survey 2005–2009, the 1990 census, the 1980 census and 2007, 2002, 1997, 1992, 1987, 1982 and 1977 economic censuses. The files we will be exploring are the subjects of Education and Population — Total and Selected Characteristics. For this purpose, I created a series of functions that could read in and parse CSV files from URLs using package readr, for different calls for each CSV file. The project in itself was divided into three main parts. 

# Key Takeaways 
The project was crucial in learning to build modularization which is of utmost importance for developing a production-ready code. It taught us the flow that is necessary during data processing activities. Actions such as renaming, pivoting, adding new columns (sometimes conditionally), and working with date columns were some of the key takeaways of the project. I learnt about the different sets of packages that work in perfect harmony under the tidyverse-universe. Chaining/piping helped in creating a clean and concise without taking up too much memory and storing multiple variables that are difficult to follow along. The project re-instilled the importance of data processing and manipulation in me. Looking at the initial structure of the dataset, it was so difficult to visualize any kind of analysis or insights that the data would provide. But like they say, "No data is clean but most data is useful." To bridge this gap between clean data and making it useful, data processing and manipulation are of utmost importance. 

# Improvement Areas 
Since we did not have the opportunity of exploring ggplot yet, the plotting part of the project felt mechanical. I would have liked the creative freedom of creating custom visualizations to understand the importance of data processing before moving to exploratory data analysis. I wish I had merged my development with Github so that I would have more version control and this is something that I wish to implement in the following project. 

To view my project, make sure to check out the ![Github Pages site](https://sneha-k.github.io/Project1.html). I look forward to hearing your thoughts and am happy to receive your feedback on it!
